---

- hosts: all
  gather_facts: yes
  vars_files:
    - linuxvolume.yml
  tasks:
    - name: List all Partitions
      shell: parted -l
      register: all_partition
    - debug: msg="{{all_partition}}"

    - name: fetch total volume size of server
      shell: parted -l | head -2 |sed '1d' | cut -d ":" -f2
      register: volume_size
    - debug: msg="{{volume_size.stdout}}"
   
    - name: Setting Variables values
      set_fact:
        servervolume: "{{volume_size.stdout}}"
        requiredvolume: "{{total_volume_size}}"

    - name: Results
      debug: 
         msg: "criteria matched"
      when: servervolume >= requiredvolume

    - name: Results
      debug: 
         msg: "criteria not matched"
      when: servervolume < requiredvolume


