---

- hosts: all
  gather_facts: yes
  vars_files:
    - linuxvolume.yml
  tasks:
    - name: List all Partitions
      shell: fdisk -l
      register: all_partition
    - debug: msg="{{all_partition}}"

    - name: fetch total volume size of server
      shell: fdisk -l | grep /dev/xvda | head -1 | cut -d ":" -f2 | cut -d "," -f1
      register: volume_size
    - debug: msg="{{volume_size.stdout}}"
   
    - name: Setting Variables values
      set_fact:
        servervolume: "{{volume_size.stdout}}"
        requiredvolume: "{{total_volume_size}}"
    
    - debug: "required volume is :" "{{requiredvolume}}"

    - name: Results
      debug: 
         msg: "criteria matched"
      when: servervolume >= requiredvolume

    - name: Results
      debug: 
         msg: "criteria not matched"
      when: servervolume < requiredvolume


